# Generated by Django 3.2.16 on 2023-06-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230615_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='placementStatus',
            field=models.BooleanField(default=False),
        ),
    ]
