# Generated by Django 3.2.16 on 2023-06-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentinfo_placementstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='contact',
        ),
    ]
