# Generated by Django 3.2 on 2023-07-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230627_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='resume',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
