# Generated by Django 3.2 on 2023-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
