# Generated by Django 3.2 on 2023-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_studentinfo_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
