# Generated by Django 3.2 on 2023-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_studentinfo_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
