# Generated by Django 4.2.2 on 2023-07-15 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_studentinfo_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='PostInfo',
        ),
    ]
