# Generated by Django 4.2.2 on 2023-07-15 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_rename_studentinfo_postinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postinfo',
            old_name='branch',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='postinfo',
            old_name='degree',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='postinfo',
            old_name='degreePercentage',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='mobno',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='placementStatus',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='yop',
        ),
        migrations.AddField(
            model_name='postinfo',
            name='average_investment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='explain',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
