# Generated by Django 4.2.2 on 2023-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_branch_postinfo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='investment_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
