# Generated by Django 4.2.2 on 2023-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_postinfo_investment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='investment_file',
            field=models.FileField(null=True, upload_to='media/files/'),
        ),
    ]
